"""empty message

Revision ID: 04aef60d3294
Revises: 60d3967d8054
Create Date: 2018-09-18 22:55:22.763256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04aef60d3294'
down_revision = '60d3967d8054'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('date_posted', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog', 'date_posted')
    # ### end Alembic commands ###
